### ISSUE TITLE
use postgres 11?

### ISSUE THREAD

**Issue by aepyornis** [JustFixNYC/nycdb-k8s-loader#8]
The server is running an older version of postgres -- 9.6 -- although nycdb is only tested with postgres 11. Is there a reason why postgres 9.6 is used? (I ask because if you are required to use an older version, I should also test with 9.6 so I don't inadvertently use a function that's only available in later versions)

**Comment by romeboards** [comment]
Good question - there's no actual reason, we've just been using 9.6 and I recall my local machine breaking the one time I tried 10. But we can and should!

**Comment by toolness** [comment]
Oh, heh, I actually am using 9.6 just because [Who Owns What's `docker-compose.yml`](https://github.com/JustFixNYC/who-owns-what/blob/master/docker-compose.yml) specifies it I think, but I'm not sure if there's any actual necessity behind it... @romeboards do you know what version of Postgres WoW uses in production?

Oh wait, come to think of it, right now the sandbox DB uses Amazon Aurora, which as of September 2018 was [upgraded to be compatible with Postgres 9.6.9](https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-aurora-with-postgresql-compatibility-supports-minor-version-9-6-9/), so I guess there's that... hmm.  I guess we could just use regular ol' Postgres instead of Aurora (Aurora supposedly provides performance benefits or something).

**Comment by aepyornis** [comment]
cool. i have no experience with aurora or really ever heard of it and anyways, i may have been bringing up a moot point because apparently `nycdb` works fine with 9.6.

**Comment by toolness** [comment]
Ok cool, I am going to close this issue then but we can re-open it if we decide that using a newer version of postgres is needed.
